server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: 172.16.250.141:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: demo-test
